# This is a sample of the configuration file (btpm_config.conf) for the
# BT policy manager. Each project should have its own btpm_config.conf file.
# The btpm_config.conf file should be put under etc/bluetooth folder
# If this file doesn't exist in etc/bluetooth,
# BT policy manager will use the default policy defined in bt_policy_manager.c

# This section is for BLE connection parameters
[BleConnParams]
BleMaxConnection = 4
# The values of BleBgConnScan parameteres should be in # of slots
# 180 means 112.5 ms (180*0.625ms)
# Slow [1.28s, 30ms]
# Medium [112.5ms, 32.5ms]
# Fast [60ms, 30ms]
BleBgConnScanSlowInterval = 2048
BleBgConnScanSlowWindow = 48
BleBgConnScanMediumInterval = 180
BleBgConnScanMediumWindow = 52
BleBgConnScanFastInterval = 96
BleBgConnScanFastWindow = 48

# The values of BLE connection interval should be in # of 1.25ms
# Peripheral latency for the connection is in number of connection events
# Tout is in (N * 10 ms)
#
# Four BLE connection parameter levels are defined
# 0: slow: 120-120ms (96-96), 0, 500
# 1: medium 1: 60-60ms (48-48), 0, 500
# 2: medium 2: 30-30ms (30-30), 0, 500
# 3: fast: 15-15ms (11-11), 0, 500
BleConnParamSlowIntMin = 96
BleConnParamSlowIntMax = 96
BleConnParamSlowLatency = 0
BleConnParamSlowTout = 500
BleConnParamMed1IntMin = 48
BleConnParamMed1IntMax = 48
BleConnParamMed1Latency = 0
BleConnParamMed1Tout = 500
BleConnParamMed2IntMin = 24
BleConnParamMed2IntMax = 24
BleConnParamMed2Latency = 0
BleConnParamMed2Tout = 500
BleConnParamFastMin = 12
BleConnParamFastMax = 12
BleConnParamFastLatency = 0
BleConnParamFastTout = 500

# Each application should have a section
# The section name should be [APP#], where # is the App ID number starting from 1
# The maximum APP ID number is 254.
# The App ID here must match the App ID provided by the application.
# The predefined APP IDs are listed below
# BTPM_APPID_FFS 1
# BTPM_APPID_RESERVED 2
# BTPM_APPID_SMARTHOME 3
# BTPM_APPID_GADGETS 4
# BTPM_APPID_HOGP 5
# BTPM_APPID_AMZN_REMOTE 6
# BTPM_APPID_BLE_MESH 7

# BTPM_APPID_FFS
[APP1]
# AppBleBgConnScanLevel value should be in range [0, 2]
# 0: slow scan; 1: medium scan; 2: fast scan
AppBleBgConnScanLevel = 1
# AppBleDedicatedLinks value should be 0 or 1.
# Only one dedicated link is allowed for a specific APP.
# The AppBleDedicatedLinks configuration needs to be approved by BT team.
AppBleDedicatedLink = 0
# AppBleXXXConnParamLevel should be in range [0, 3]
# 0: slow: 100-125ms (80-100), 0, 500
# 1: medium 1: 30-50ms (24-40), 0, 500
# 2: medium 2: 37.5-37.5ms (30-30), 0, 500
# 3: fast: 13.75-13.75ms (11-11), 0, 500
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 2

# BTPM_APPID_RESERVED
[APP2]
AppBleBgConnScanLevel = 0
AppBleDedicatedLink = 0
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 1

# BTPM_APPID_SMARTHOME
[APP3]
AppBleBgConnScanLevel = 2
AppBleDedicatedLink = 0
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 2

# BTPM_APPID_GADGETS
[APP4]
AppBleBgConnScanLevel = 1
AppBleDedicatedLink = 0
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 1

# BTPM_APPID_HOGP
[APP5]
AppBleBgConnScanLevel = 0
AppBleDedicatedLink = 1
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 1

# BTPM_APPID_AMZN_REMOTE
[APP6]
AppBleBgConnScanLevel = 1
AppBleDedicatedLink = 0
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 2

# BTPM_APPID_BLE_MESH
[APP7]
AppBleBgConnScanLevel = 1
AppBleDedicatedLink = 1
AppBleDirConnParamLevel = 3
AppBleBgConnParamLevel = 1
